Framework/Images/Packer.cs

- Fixes Packer.Add() index parameter passthrough bug.
- Fixes SpriteFont constructor failing.

Fixed index parameter passthrough for Packer.Add() overload

---

Platform/CMakeLists.txt

Fixes #26. Because the GitHub runners are intel-based, the macOS binaries of the platform lib built in the Actions workflow were only compatible with x64 machines. To solve this issue, following [this SO answer](https://stackoverflow.com/questions/65157483/macos-build-universal-binary-2-with-cmake), a CMake option is included to build universal binaries on macOS, allowing the library to run on arm machines.

Building universal binary of platform lib on macOS

---

Framework/Extensions/VectorExt.cs
Framework/Images/Color.cs

*Add FloorToPoint2 extension method
*Add CornflowerBlue color just for fun.
Question:
Should we prefer using 'Calc' class over making direct calls to Math or MathF ?
In the 'VectorExt.cs'  'MathF.Round' is used, even though comment on method 'Calc.Round' says "Always round using this!"

Two little things.

---

Framework/Graphics/SpriteFont.cs
Framework/Images/Font.cs

`Font(string path)` now uses `File.OpenRead`, `SpriteFont` now disposes `Font` where possible.

Font(string path) now uses File.OpenRead, SpriteFont now disposes Font where possible

---

Framework/Graphics/Subtexture.cs

Mark properties and methods as readonly, so the batcher does not generate defensive copies of Subtextures.

Try to avoid defensive copies in batcher

---

Framework/Graphics/Material.cs

`for` loops are ~2x faster for small `List`s (that we typically deal with here).
In a degenerate case where two alternating textures are drawn via `Batcher`, the time decreases for these methods (percent time in release mode):
- `Material.Get`: 11.06% -> 5.47%
- `Material.Apply`: 8.65% -> 8.09%
A benchmark via `BenchmarkDotNet` shows the improvement as well. I also tested `Dictionary`, `Array`, and `Span` (`Span` with `List` uses `CollectionsMarshal.AsSpan`). Here are the full results with 5 uniforms looking for the last uniform in the list.
<HTML>
<BODY>
<TABLE><THEAD><TH>Case</TH><TH>Mean</TH></THEAD><TR><TD>DictionaryLookup</TD><TD>13.26 ns</TD></TR><TR><TD>ArrayForeach</TD><TD>16.37 ns</TD></TR><TR><TD>ArraySpanForeach</TD><TD>16.53 ns</TD></TR><TR><TD>ArraySpanFor</TD><TD>16.55 …

Use for loops over foreach in Material.Get/Apply

---

Framework/Images/Packer.cs

`DuplicateEdges` enables copying border pixels into padding. It copies 1 pixel in each direction and only when Padding >= 2.
This helps with annoying texture bleed problems at non whole scaling/transforms for tile based games.
Additionally, subtextures are now "centered" in their packed node to allow padding on Top/Left texture page borders.

Packer DuplicateEdges flag

---

Framework/Images/Enums/ImageWriteFormat.cs
Framework/Images/Image.cs
Framework/Platform.cs
Platform/include/foster_platform.h
Platform/src/foster_image.c

QOI test seems to not work on my machine. Replaced with magic number test from `qoi_decode`.
Added QOI write functionality.
I'd be open to condense our write methods to:
- `Image.Write(string path, ImageWriteFormat format = ImageWriteFormat.Png)`
- `Image.Write(Stream stream, ImageWriteFormat format = ImageWriteFormat.Png)`
Also not sure about casing when it comes to Png/PNG, Qoi/QOI. Went with only first letter capitalized to stay consistent with existing C# methods, but open to changes here.

Fixed QOI test, added QOI write

---

Framework/App.cs
Framework/Spatial/Facing.cs
Framework/Utility/Pool.cs

XML comments will be broken if there are angle brackets or other XML reserved characters in them
also, "see cref" s would be more friendly to IDE prompts and document generation 🌱

xml comment fixes & use "see cref"

---

Platform/include/foster_platform.h
Platform/src/foster_image.c
Platform/src/foster_internal.h
Platform/src/foster_platform.c
Platform/src/foster_renderer.h

Avoid usage of bool (as it has C# issues) and add FosterBool (which is typedef to uint8_t/byte C#), as per https://github.com/NoelFB/Foster/commit/9852f3e3b75fbfe119ddf3063b4fd398b8caf5a2

Avoid usage of bool in foster_platform.h

---

Framework/Images/Aseprite.cs

Since content API (#37) returns stream objects, we should be able to load Aseprite directly from these.

Add  constructor: Aseprite(Stream stream)

---

Platform/src/foster_renderer_opengl.c

When running Celeste64 from the command line a bunch of errors are generated of the form `GL (ERROR:HIGH) GL_INVALID_ENUM in glDrawBuffers(invalid buffer GL_BACK)`.  I don't believe there's any meaningful impact on the rendering being done, but for the sake of a tidy command line this tiny patch addresses that error message.
References I used:
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDrawBuffers.xhtml
https://www.khronos.org/opengl/wiki/Default_Framebuffer
https://registry.khronos.org/OpenGL/api/GL/glcorearb.h

Avoid GL_INVALID_ENUM generation by glDrawBuffers

---

Platform/CMakeLists.txt

Update SDL to stable 2.30.0 release (https://github.com/libsdl-org/SDL/releases/tag/release-2.30.0)

Update SDL to stable 2.30.0 release

---

Platform/src/foster_platform.c

On some platforms `SDL_GetWindowPosition` will always return 0,0 while mouse position is still absolute. This would result in an absolute position inside `Input.Mouse.Position` instead of a relative one.
This PR lets SDL handle the relative positioning.

Use relative mouse API

---

Platform/src/foster_platform.c

Added SDL_Quit() in FosterShutdown()

---

Framework/Graphics/Batcher.cs

This closes #78. I've added a few overload variations to it w/ some transormations like the other `Image` methods have. Let me know if I missed anything.

Add `Batcher.ImageStretch` for rendering stretched images

---

Framework/Input/Input.cs
Framework/Input/Mouse.cs
Framework/Platform.cs
Platform/include/foster_platform.h
Platform/src/foster_platform.c

Feel free to kick this PR into a lake if it's not considered useful (or if you're already doing this somewhere and I didn't catch that). I think its useful that SDL already provides this as part of it's input subsystem, so this PR exposes includes the relative mouse position as part of the input state.

Include the mouse delta as part of the input state

---

Framework/Foster.Framework.csproj

this is to allow xml documentation to be viewed from the nupkg and possibly displayed from a static site like https://dotnet.github.io/docfx/

include xml documentation

---

Framework/Internal/Renderer.cs

* Separate command buffers for copy/render commands to allow for better throughput
* Now use shared transfer buffer when reasonable (<16MB) and single use transfer buffers when larger
* Lots of this is based on the SDL_GPU driver in FNA3D, and likely needs review
* Aside from the TODO comments added here, I've made some notes in #1
* Overall these changes allow for better throughput with synthetic benchmark performance on par with (actually a little better than) the current OpenGL implementation in main

SDL_GPU: Use separate command buffers for copy/render, shared transfer buffers

---

Framework/App.cs
Framework/Window.cs

`AppConfig.Resizable` was not being passed into `Window.ctor`, so the application's window would be resizable even if you disabled it.

Initialize the window resizable flag with the initial value (provided in `AppConfig`)
